export const UPDATE_TICKERS = 'UPDATE_TICKERS';
export const SET_SELECTED_TICKER = 'SET_SELECTED_TICKER';
export const UPDATE_INVESTORS = 'UPDATE_INVESTORS';
export const SET_LOADING = 'SET_LOADING';
export const TOAST_ERROR = 'TOAST_ERROR';
export const TOAST_SUCCESS = 'TOAST_SUCCESS';
export const TOAST_WARNING = 'TOAST_WARNING';
